### ISSUE TITLE
Crash after previewing a PDF file and then a JPG file

### ISSUE THREAD

**Issue by mgrojo** [thindil/hunter#2] opened 2020-01-07 19:06 UTC
Hunter crashes after these steps:

1. Download https://github.com/thindil/hunter/releases/download/1.1/hunter-x86_64.AppImage
1. Download attached PDF and JPG file to an empty directory.
2. Run: `hunter-x86_64.AppImage directory`
2. Preview the PDF file and then the JPG file
3. Hunter crashes and the content of the ~/.cache/hunter/error.log is as attached file.

Thanks for your interesting Ada project.

[mapa.pdf](https://github.com/thindil/hunter/files/4032033/mapa.pdf)
[portada_time](https://user-images.githubusercontent.com/13812910/71921017-4cade700-3188-11ea-9117-cd322757e139.jpg)
[error.log](https://github.com/thindil/hunter/files/4032034/error.log)

**Comment by thindil** [comment] 2020-01-07 20:43
Hello, thank you very much for your report (and kind words :)) and I'm sorry for problems.  I will try to check it. There can be a small problem probably with reproduce it, because currently Hunter is under heavy rewrite, but we will see.

**Comment by thindil** [comment] 2020-01-18 06:22
Ok, new version is available and I hope, this bug is fixed in it also :) Thus I close this issue. Again, thank you very much for the report. If you disagree with closing or bug will happen again, feel free to reopen this issue or create new.

**Closed as completed by thindil** 2020-01-18 06:22 UTC
Labels: bug
